### ISSUE TITLE
Add clickhouse helm chart to the official altinity clickhouse repo

### ISSUE THREAD

**Issue by Philippians413** [slamdev/helm-charts#21]
Hello!

Today helm is a very popular tool for installing components to k8s cluster and maybe it would be better to create PR to the official Altinity repo https://github.com/Altinity/clickhouse-operator/tree/master/deploy ?

Your helm chart looks pretty cool, good work :+1:

**Comment by slamdev** [comment]
I guess it's better to open this issue in altinity repo and not here :)
afaik there were multiple attempts to create an official helm chart. feel free to use this one as a starting point

https://github.com/Altinity/clickhouse-operator/issues/620
