### ISSUE TITLE
altinity-clickhouse-operator nodeSelector: does not have any effect

### ISSUE THREAD

**Issue by olexiyb** [slamdev/helm-charts#23]
`nodeSelector:` described in https://github.com/slamdev/helm-charts/blob/master/charts/altinity-clickhouse-operator/values.yaml is not applied to deployment as expected

**Comment by slamdev** [comment]
@olexiyb thanks for reporting the bug. sorry it took so long to fix.

https://github.com/slamdev/helm-charts/commit/92873a43671d8acbb561ebdf5851df4472958b06
