### ISSUE TITLE
Envoy pod disruption budget and scaling

### ISSUE THREAD

**Issue by artificial-aidan** [slamdev/helm-charts#37]
Are you open to a PR adding a pod disruption budget and horizontal pod autoscaler to the envoy chart?

Something like this for the pdb: https://github.com/helm/charts/blob/master/stable/envoy/templates/poddisruptionbudget.yaml

Or would you rather these just be added using the `additionalResources` field.

**Comment by slamdev** [comment]
@artificial-aidan I recently pushed an ability to add any additional resources to the envoy chart via this value: https://github.com/slamdev/helm-charts/blob/master/charts/envoy/values.yaml#L151

I think it covers your requirement. If not, let me know

**Comment by artificial-aidan** [comment]
I think that will work. I don't think I realized they were run through `tpl` that makes it easier.
