### ISSUE TITLE
No license specified: Not allowed to fork and modify

### ISSUE THREAD

**Issue by gjkamstra** [slamdev/helm-charts#4]
There is no license available in this repo. This means we need to assume it cannot be forked and modified without permission.
Can you please add a license? (MIT recommended)

_If a repository has no license, then all rights are reserved and it is not Open Source or Free. You cannot modify or redistribute this code without explicit permission from the copyright holder._

From https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license#:~:text=If%20a%20repository%20has%20no,permission%20from%20the%20copyright%20holder

**Comment by slamdev** [comment]
done. thanks for pointing this out!
