### ISSUE TITLE
How do you  generate helm yaml templates for  clickhouse deployment ?

### ISSUE THREAD

**Issue by kksudo** [slamdev/helm-charts#6]
I saw the [sync-yamls.sh](https://github.com/slamdev/helm-charts/blob/master/charts/altinity-clickhouse-operator/hacks/sync-yamls.sh) file, but I didn't find  any converting logic from k8s manifest to helm templates.
Could  you please describe the generate process in two words, or its manual work ?

**Comment by slamdev** [comment]
@kksudo it is indeed manual: I am running the script and the go file by file checking if anything important was changed and adjusting it manually
